create table cat_entity
(
    id      int8 generated by default as identity,
    image   varchar(255),
    message varchar(255),
    name    varchar(255),
    primary key (id)
);

create table mimi_user
(
    id              int8 generated by default as identity,
    activation_code varchar(255),
    email           varchar(255),
    name            varchar(255) not null,
    password        varchar(255),
    primary key (id)
);
create table user_role

(
    user_id int8 not null,
    roles   varchar(255)
);
create table vote_entity

(
    id        int8 generated by default as identity,
    vote      boolean not null,
    author_id int8    not null,
    cat_id    int8    not null,
    primary key (id)
);

alter table if exists cat_entity
    add constraint UKaehg34lgii4ln48ev8ojtj71i unique (name, image);
alter table if exists mimi_user
    add constraint UK_4jlknowedol5jnabc0b49t1la unique (name);
alter table if exists user_role
    add constraint UK_apcc8lxk2xnug8377fatvbn04 unique (user_id);
alter table if exists vote_entity
    add constraint UKk4jmj19jiqx7vul63b9w64lid unique (author_id, cat_id);
alter table if exists user_role
    add constraint FKg9q9t3n5a52d95ibbvupkknac foreign key (user_id) references mimi_user;
alter table if exists vote_entity
    add constraint FKksm8y3pqcx78x3j3moimld7n3 foreign key (author_id) references mimi_user;
alter table if exists vote_entity
    add constraint FKotc5yl3qqk309ftdfxc0ykgmg foreign key (cat_id) references cat_entity;